### ISSUE TITLE
Failing to retrieve repo list

### ISSUE THREAD

**Issue by ithinkido** [RomeHein/ESPInstaller#2]
I am having a difficult time getting the repository list. 
The code was not modified except for the wifi credentials and was complied on Arduino 1.18.15 using ESP32 library 1.0.6.
Here is the serial output:
```[SETUP] Connecting to wifi
.....[SETUP] CONNECTED
[SETUP] Web interface available on: esp-installer or 192.168.178.60
[Server]: init
[SERVER] Retrieving repo list from https://raw.githubusercontent.com/RomeHein/ESPInstaller/master/list.json
[SERVER] Could not get repo list. Error -1: connection refused
[SERVER] Retrieving repo list from https://raw.githubusercontent.com/RomeHein/ESPInstaller/master/list.json
[SERVER] Could not get repo list. Error -1: connection refused
```

Is there something I need to change to use the updater ?

**Comment by RomeHein** [comment]
Interesting, I'll try to have a look a it today. This might come from an issue with the HTTPS call.

EDIT:
Ok, I'm sorry the only EPS32 I have at the moment seems to be broken, I need to buy some before testing anything. Sorry for the delay.

**Comment by ithinkido** [comment]
Ok, no problem. I am not in a hurry.

**Comment by rj10rd** [comment]
> I am having a difficult time getting the repository list. The code was not modified except for the wifi credentials and was complied on Arduino 1.18.15 using ESP32 library 1.0.6. Here is the serial output:
> 
> ```
> .....[SETUP] CONNECTED
> [SETUP] Web interface available on: esp-installer or 192.168.178.60
> [Server]: init
> [SERVER] Retrieving repo list from https://raw.githubusercontent.com/RomeHein/ESPInstaller/master/list.json
> [SERVER] Could not get repo list. Error -1: connection refused
> [SERVER] Retrieving repo list from https://raw.githubusercontent.com/RomeHein/ESPInstaller/master/list.json
> [SERVER] Could not get repo list. Error -1: connection refused
> ```
> 
> Is there something I need to change to use the updater ?


> Interesting, I'll try to have a look a it today. This might come from an issue with the HTTPS call.
> 
> EDIT: Ok, I'm sorry the only EPS32 I have at the moment seems to be broken, I need to buy some before testing anything. Sorry for the delay.



> I am having a difficult time getting the repository list. The code was not modified except for the wifi credentials and was complied on Arduino 1.18.15 using ESP32 library 1.0.6. Here is the serial output:
> 
> ```
> .....[SETUP] CONNECTED
> [SETUP] Web interface available on: esp-installer or 192.168.178.60
> [Server]: init
> [SERVER] Retrieving repo list from https://raw.githubusercontent.com/RomeHein/ESPInstaller/master/list.json
> [SERVER] Could not get repo list. Error -1: connection refused
> [SERVER] Retrieving repo list from https://raw.githubusercontent.com/RomeHein/ESPInstaller/master/list.json
> [SERVER] Could not get repo list. Error -1: connection refused
> ```
> 
> Is there something I need to change to use the updater ?

Same problem here
Is there any solution available?

**Comment by RomeHein** [comment]
omg, i'm so sorry guys!
completely forgot about that one. I'll try to do my best to find a solution this week.

**Comment by RomeHein** [comment]
Ok guys, that's weird, I don't have any issues retrieving the list:
```
13:01:13.925 -> .[SETUP] CONNECTED
13:01:13.925 -> [SETUP] Web interface available on: esp-installer or 192.168.1.114
13:01:13.925 -> [Server]: init
13:01:37.344 -> [SERVER] Retrieving repo list from https://raw.githubusercontent.com/RomeHein/ESPInstaller/master/list.json
13:01:38.686 -> [SERVER] repo list retrieved: [
13:01:38.686 ->     {
13:01:38.686 ->         "name": "ESPecial",
13:01:38.720 ->         "description": "This project aim to provide an easy way to control your esp32. You no longer need programming skills to set complex tasks. This can be a very nice approach for small projects, home automation and/or educational purposes.",
13:01:38.720 ->         "repoRawPath": "https://raw.githubusercontent.com/RomeHein/ESPecial/master/versions/"
13:01:38.720 ->     },
13:01:38.720 ->     {
13:01:38.720 ->         "name": "ESPInstaller",
13:01:38.754 ->         "description": "A simple webserver to allow easy installation of other project directly from their repo",
13:01:38.754 ->         "repoRawPath": "https://raw.githubusercontent.com/RomeHein/ESPInstaller/master/versions/"
13:01:38.754 ->     }
13:01:38.754 -> ]
```

Could you try to make the fallowing command on your shell terminal, or cmd, from the same wifi network you are connecting your esp32:
```
curl https://raw.githubusercontent.com/RomeHein/ESPInstaller/master/list.json
```
I'd like to see if you are still able to retrieve the list.json from this repo.

**Comment by soerenbrogaard** [comment]
I'm also experiencing the issue. I can curl the file just fine from the same network..

**Comment by soerenbrogaard** [comment]
just tried serving the json via http on a webserver and changed the WiFiClientSecure to WiFiClient and that worked. So it would indeed seem as if the SSL communication is the issue. 

I used ESPInstaller successfully about a year ago - no issues then.

**Comment by soerenbrogaard** [comment]
just a quick follow up - downgrading to esp32 1.0.4 through the Arduino IDE Boards Manager seemed to resolve the issue for me. (I was using 1.0.6 previously) Unfortunately I don't have the time to investigate the changelog further between the versions at the moment. But hopefully this will help others work around the issue for the time being :-)

**Comment by RomeHein** [comment]
Very nice, thanks for your help. I'll try that tomorrow, to check if I can reproduce the issue. 👏👏

**Comment by soerenbrogaard** [comment]
No problem! Thank you for the great project :-)
The change causing the issue is here: https://github.com/espressif/arduino-esp32/pull/4648

So while insecure, simply adding "client.setInsecure();" works for newer versions ;-)

**Comment by RomeHein** [comment]
Nice one! My esp32 board manager version was really old (1.0!), updating gave me the same error. Thanks!
I think this is ok to set `client.setInsecure()`. Is there a use case here where we would want secure connection to a repo?

**Comment by soerenbrogaard** [comment]
I cannot see anything wrong with it from a pragmatic point of view. The cert wasn't being validated before either so it's not a regression or anything. Though I am unsure if I am fully able to comprehend the implications..

**Comment by RomeHein** [comment]
Yep me neither 🤷🏻‍♂️ Ok let's push that fix. If someone can explain us how it's bad and propose a better solution I'll reopen that issue. Thanks again for your help!

**Comment by RebbePod** [comment]
Was the changed pushed? Still getting the error

**Comment by RomeHein** [comment]
Thanks @RebbePod for the reminder. It's pushed and fixed.

**Comment by aurelien31430** [comment]
Hello, I want to install especial but it does not appear in the esp-installer list

it gives me this problem:
[SERVER] Retrieving repo list from https://raw.githubusercontent.com/RomeHein/ESPInstaller/master/list.json
[SERVER] Could not get repository list. Error -5: connection lost

when I do curl https://raw.githubusercontent.com/RomeHein/ESPInstaller/master/list.json

There it works without problem, it displays the list.

In: Install from custom URL I don't know what to put as url

and in: Install from local directory

when I select the file nothing happens :(

HELP ME
